name: Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.0'

      - name: Setup emsdk
        run: |
          git clone https://github.com/emscripten-core/emsdk
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
          ./emsdk construct_env

      - name: Build irb
        run: |
          source emsdk/emsdk_env.sh
          ./build.sh

      - name: Publish
        uses: cloudflare/pages-action@v1.5.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: irb-ruby-uy
          directory: docs
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          wranglerVersion: '3'
